version: '3.10'
services:
    app:
        build: .
        image: apilogin:v1.4.8
        volumes:
            - /data/profile:/data/profile
        container_name: apilogin
        command: uvicorn app.main:app --proxy-headers --host 0.0.0.0 --port 8000
        ports:
            - "8000:8000"
volumes:
    volapilogin:
        name: volapilogin