version: '3.10'
services:
    app:
        build: .
        container_name: loginypw
        command: uvicorn app.main:app --proxy-headers --host 0.0.0.0 --port 8000
        ports:
            - "8000:8000"